run:
  deadline: 5m
  issues-exit-code: 10
  modules-download-mode: vendor

output:
  format: colored-line-number

linters-settings:
  errcheck:
    check-blank: false
    check-type-assertions: true

  govet:
    check-shadowing: true

  golint:
    min-confidence: 0.5

  gofmt:
    simplify: true

  goimports:
    local-prefixes: github.com/org/project

  gocyclo:
    min-complexity: 10

  maligned:
    suggest-new: true

  dupl:
    threshold: 100

  goconst:
    min-len: 3
    min-occurrences: 3

  misspell:
    locale: US

  lll:
    line-length: 120
    tab-width: 1

  unused:
    check-exported: false

  unparam:
    check-exported: false

  nakedret:
    max-func-lines: 50

  prealloc:
    simple: true
    range-loops: true
    for-loops: false

linters:
  enable-all: true
  disable:
    - goimports
